version: '3.8'

# Development overrides for docker-compose.yml
# This file automatically applies when using docker-compose up

services:
  research-agent:
    build:
      target: builder  # Use development stage if multi-stage build supports it
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      # Mount source code for development hot-reload
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./requirements.txt:/app/requirements.txt:ro
    command: ["uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    
  # Development database with exposed data
  postgres:
    environment:
      - POSTGRES_DB=research_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass
    volumes:
      - ./data/dev-db:/var/lib/postgresql/data
      
  # Development Redis with persistence disabled for faster startup
  redis:
    command: redis-server --save ""