version: '3.8'

# Production configuration for docker-compose
# Use: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  research-agent:
    image: ghcr.io/university/faculty-research-notifier:latest
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
      - WORKERS=4
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    # Remove volume mounts for source code
    volumes:
      - ./data:/app/data:ro
      - ./config:/app/config:ro
      - ./logs:/app/logs
    
  postgres:
    environment:
      - POSTGRES_DB=research_prod
      - POSTGRES_USER=research_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./backups:/backups
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      
  redis:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfsync everysec
      
  # Load balancer for production
  nginx:
    profiles: ["production"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  postgres_prod_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/research-agent/data/postgres

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt