global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@research-system.local'
  smtp_auth_username: 'alerts@research-system.local'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match:
        category: security
      receiver: 'security-alerts'
      group_wait: 10s

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@research-system.local'
        subject: '[CRITICAL] Research System Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          Service: {{ .GroupLabels.service }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}
          
          View in Grafana: http://localhost:3000
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: 'Critical Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@research-system.local'
        subject: '[WARNING] Research System Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          Service: {{ .GroupLabels.service }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}
          
          View in Grafana: http://localhost:3000

  - name: 'security-alerts'
    email_configs:
      - to: 'security@research-system.local'
        subject: '[SECURITY] Research System Security Alert: {{ .GroupLabels.alertname }}'
        body: |
          Security Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          Severity: {{ .GroupLabels.severity }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}
          
          Immediate investigation required.
          View logs and metrics: http://localhost:3000

inhibit_rules:
  # Inhibit warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']